---
type: string
enum:
- IOS_DEVELOPMENT
- IOS_DISTRIBUTION
- MAC_APP_DISTRIBUTION
- MAC_INSTALLER_DISTRIBUTION
- MAC_APP_DEVELOPMENT
- DEVELOPER_ID_KEXT
- DEVELOPER_ID_APPLICATION
- DEVELOPMENT
- DISTRIBUTION
- PASS_TYPE_ID
- PASS_TYPE_ID_WITH_NFC
