---
type: string
enum:
- PROCESSING
- PROCESSING_EXCEPTION
- MISSING_EXPORT_COMPLIANCE
- READY_FOR_BETA_TESTING
- IN_BETA_TESTING
- EXPIRED
- READY_FOR_BETA_SUBMISSION
- IN_EXPORT_COMPLIANCE_REVIEW
- WAITING_FOR_BETA_REVIEW
- IN_BETA_REVIEW
- BETA_REJECTED
- BETA_APPROVED
