---
type: string
enum:
- MISSING_METADATA
- WAITING_FOR_UPLOAD
- PROCESSING_CONTENT
- READY_TO_SUBMIT
- WAITING_FOR_REVIEW
- IN_REVIEW
- DEVELOPER_ACTION_NEEDED
- PENDING_BINARY_APPROVAL
- APPROVED
- DEVELOPER_REMOVED_FROM_SALE
- REMOVED_FROM_SALE
- REJECTED
