name: Check for updates

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-for-updates:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download spec
        run: .github/scripts/spec/check-for-updates.sh
      - name: Configure git
        run: .github/scripts/git/configure.sh
      - name: Create pull request
        run: .github/scripts/git/create-pull-request.sh
