name: Check for updates

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-for-updates:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git
        run: .github/scripts/git/configure.sh
      - name: Download spec
        id: spec
        run: .github/scripts/spec/check-for-updates.sh
      - name: Create pull request
        run: .github/scripts/spec/create-pull-request.sh "$version"
        env:
          version: ${{ steps.spec.outputs.spec_version }}
